spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db?options=-c%20timezone=Asia/Kolkata
    username: portfolio_user
    password: portfolio_password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: OFF

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true