spring:
  application:
    name: portfolio-backend

info:
  app:
    version: @project.version@
    description: Portfolio Consultation Backend API

  profiles:
    active: debug

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080
  shutdown: graceful